#' Refits a functional linear model to bootstrap samples
#'
#' @description Takes a functional linear model generated by refund::pffr and re-estimates the model coefficients on a set of bootstrap samples.
#'
#' @param model A pffr model object.
#' @param boot.list A list of dataframes to re-estimate the model.
#' @param ncores Specifies the number of cores to use in parallel processing. Defaults to 4.
#'
#' @return A list of lists. Each list object contains 2 items 'orginal' which is the original coefficient and standard error estimates, and 'boots' which is a matric of bootstrap replicates.
#'
#' @import refund
#' @importFrom future plan
#' @import future.apply future_lapply
#' @export
fit.boots = function(model, boot.list, ncores = 4){

  message("Setting up cluster")
  # set up cluster
  plan(multisession, workers = ncores)   # or whatever plan you prefer

  # extract model and data basics
  B = length(boot.list)

  yind = mod$pffr$yind

  int = length(which(names(model$coefficients) == "(Intercept)")) == 1

  # set up messaging
  msg.points = seq(0, B, 100)

  #refit model
  out = future_lapply(X = 1:B, FUN = function(i){

    if(i %in% msg.points){message(paste0(i, " of ", B, " iterations completed."))}

    mod.call = model$pffr$call

    mod.call$data = boot.list[[i]]

    mod.call$yind = yind

    refit = suppressWarnings({suppressMessages({eval(mod.call)})})

  }, future.packages = "refund")

  # close cluster
  plan(sequential)

  #extract coefs
  out = lapply(out, function(x){
    invisible(capture.output(coef_x <- coef(x)))

    # combine intercepts if present
    if(int){
      coef_x[[2]][[1]]$coef$value = coef_x[[2]][[1]]$coef$value + coef_x[[1]][1]
    }

    lapply(coef_x[[2]], function(p){
      p$coef$value
    })
  })

  # extract original estimates
  invisible(capture.output(coefs <- coef(model)))

  if(int){
    coefs[[2]][[1]]$coef$value = coefs[[2]][[1]]$coef$value + coefs[[1]][1]
    coefs[[2]][[1]]$coef$se = coefs[[2]][[1]]$coef$se + coefs[[1]][2]}

  P <- length(out[[1]])

  out <- lapply(seq_len(P), function(p) {
    do.call(cbind, lapply(seq_len(B), function(b) out[[b]][[p]]))
  })



  out = lapply(1:P, function(p){list("original" = coefs[[2]][[p]]$coef, "boots" = out[[p]])})
  names(out) = names(coefs[[2]])
  out
}
